version: "3.8"

services:
  app:
    build: .
    container_name: risk_analysis_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: risk_analysis_db
    restart: always
    environment:
      POSTGRES_USER: riskuser
      POSTGRES_PASSWORD: riskpass
      POSTGRES_DB: riskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./pgdata
      o: bind
