-- schema.sql

-- Table to store ACLED conflict events
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='conflict_events' AND xtype='U')
BEGIN
    CREATE TABLE conflict_events (
        id INT IDENTITY(1,1) PRIMARY KEY,
        event_date DATE NOT NULL,
        event_type VARCHAR(100),
        sub_event_type VARCHAR(100),
        actor1 VARCHAR(255),
        actor2 VARCHAR(255),
        country VARCHAR(100),
        region VARCHAR(100),
        admin1 VARCHAR(100),
        admin2 VARCHAR(100),
        location VARCHAR(255),
        latitude DECIMAL(9,6),
        longitude DECIMAL(9,6)
        -- ... add other columns as needed ...
    )
END

-- Table to store World Bank economic indicators
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='economic_indicators' AND xtype='U')
BEGIN
    CREATE TABLE economic_indicators (
        id INT IDENTITY(1,1) PRIMARY KEY,
        date DATE NOT NULL,
        country VARCHAR(100) NOT NULL,
        indicator_code VARCHAR(50) NOT NULL,
        indicator_name VARCHAR(255) NOT NULL,
        value DECIMAL(18,4)
    );
END

-- Table to store governance/fragility/legal risk indicators
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='governance_indicators' AND xtype='U')
BEGIN
    CREATE TABLE governance_indicators (
        id INT IDENTITY(1,1) PRIMARY KEY,
        year INT NOT NULL,
        country VARCHAR(100) NOT NULL
        -- ...other columns...
    );
END

-- Optional: Table to store risk predictions generated by the model
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='risk_predictions' AND xtype='U')
BEGIN
    CREATE TABLE risk_predictions (
        id INT IDENTITY(1,1) PRIMARY KEY,
        prediction_date DATETIME DEFAULT GETDATE(),
        region VARCHAR(100),
        predicted_risk_level VARCHAR(50),
        probability DECIMAL(5,4),
        model_version VARCHAR(20)
    );
END
